#!/bin/bash 

if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

c_git_clean=`tput setaf 2`
c_git_dirty=`tput setaf 1`

git_prompt ()
{
    if ! git rev-parse --git-dir > /dev/null 2>&1; then
        return 0
    fi
                 
    git_branch=$(git branch 2>/dev/null| sed -n '/^\*/s/^\* //p')
    if git diff --quiet 2>/dev/null >&2; then
        git_color="${c_git_clean}"
    else
        git_color=${c_git_dirty}
    fi

    echo " $git_color[$git_branch]${c_reset}"
}

PS1="#${debian_chroot:+($debian_chroot)}"
# time
PS1="$PS1 \[\033[36m\]\t\[\033[00m\]" 
# host
PS1="$PS1 \[\033[33m\]\u@\h\[\033[00m\]:"
# current path
PS1="$PS1 \[\033[01;34m\]\w\[\033[00m\]" 
# git status
PS1="$PS1\$(git_prompt)"
# history command number
PS1="$PS1 \[\033[35m\]!\!\[\033[00m\]"
# prompt line
PS1="$PS1 \n\[\033[37m\]\$ \[\033[00m\]"

